### ISSUE TITLE
how to inference on a image

### ISSUE THREAD

**Issue by yuhao20** [cfifty/CAML#1]

**Comment by cfifty** [comment]
1. Follow the README.md to download the datasets.
2. Add your model to ```CAML/src/models/```. It needs to implement the ```meta_test``` method. 
3. Run the following command:

python src/evaluation/test.py --model ``your_model`` --gpu 0 --eval_dataset ``your_dataset``  \
--fe_type timm:vit_base_patch16_clip_224.openai:768
