### ISSUE TITLE
Pre-training with the recommended arguments, but always getting low accuracies.

### ISSUE THREAD

**Issue by ctoa2020** [cfifty/CAML#13]
Dear cfifty, 
        I tried to pre-train the CAML model with the arguments recommended in the README.md, but always got low validation accuracies about 2x% and high training losses about 1.6x. May I know if there are any details required for model training that I'm missing? Thank you.

**Comment by cfifty** [comment]
Hey, thanks for the comment. Can you add more information? What command are you using, and are you training across all of the pre-training datasets? Also upload a copy of the train.log file?
