### ISSUE TITLE
The reason why we failed to train the model has been found.

### ISSUE THREAD

**Issue by ctoa2020** [cfifty/CAML#14]
Dear cfifty,
Many thanks. We found that the reason why we failed to train CAML was using higher versions of torch 2.3.0 and torchvision 0.18.0 than the recommended versions in the "environment.yaml" which were torch 1.13.1 and torchvision 0.14.1. The attached files train1.log and train2.log show the failing training process with torch 2.3.0 and torchvision 0.18.0, and the  successful training process with torch 1.13.1 and torchvision 0.14.1, respectively.
However, when we load the checkpoint of our trained model to test the aircraft dataset  by 5-way, 5-shot, we only get an accuracy about 20.7%  as shown in the attached image file which is far below the accuracy about 77.1%  when using the default checkpoint  from the download link. So we still work on this problem to look for a possible solution.
[train1.log](https://github.com/user-attachments/files/16602587/train1.log)
[train2.log](https://github.com/user-attachments/files/16602591/train2.log)
![IMG_6149](https://github.com/user-attachments/assets/0c5c8735-c6fd-4e21-8b22-9a903e05c026)

**Comment by cfifty** [comment]
Hey -- this indicates you're at random-guess performance (20%), so (clearly) something is not working. I'd look at one of the following:

1. Make sure the image encoder you are using during testing is the same as the one you're using during training. If you train the sequence model with CLIP image embeddings, make sure CLIP image embeddings are used to encode the Aircraft dataset.

2. The concatenation between label embeddings and image embeddings is mixed up between the support and query set. See #4 

All this said, it's quite odd that you're getting this error. The models we used in the paper (and release on github) do not have this issue.

**Comment by ctoa2020** [comment]
Dear cfify,
Many thanks for your kind suggestions. We will try to make sure the two configurations you point out are set up properly and test it again.

**Comment by ctoa2020** [comment]
Dear cfify,
Our settings have been confirmed to be in accordance with the two points you indicated last time.
We also changed the entire environment to be exactly the same as the environment.yml, and except for changing the batch_size from 525 to 450 due to insufficient memory space of our GPU, the rest of the training configurations were the same as README.md. All these settings can be seen in attached images. 
The training process looked like smoothing as shown in train.log. However, when we loaded the trained model.pth for testing, the model still returned poor accuracy results as shown in attached images.
In addition, we have even tried that training the CAML by using original imagenet images without using the "cache:" mode of clip and ".npy" format images, but still got poor results in testing.
We have no idea that if there are any issues or configurations we are missing.
Many thanks.
![Screenshot 2024-09-07 15:13:23](https://github.com/user-attachments/assets/4b7e86af-0d4b-425a-a6c2-2ada5b00995c)
![Screenshot 2024-09-07 15:14:22](https://github.com/user-attachments/assets/f2be0a75-68d8-4b60-bbed-eea53e4cc96b)
![Screenshot 2024-09-07 14:48:19](https://github.com/user-attachments/assets/fe6285b8-3532-4ef0-88b0-9fa7aeb97e3e)
![Screenshot 2024-09-07 15:10:21](https://github.com/user-attachments/assets/11906a9d-5789-47f1-90c9-1bf9c5620ddb)
![Screenshot 2024-09-07 15:02:46](https://github.com/user-attachments/assets/25e61167-b40f-44fa-96b2-a688dd187bcf)
[train.log](https://github.com/user-attachments/files/16917184/train.log)

**Comment by cfifty** [comment]
Hey; I went to a fresh server, cloned the repository, downloaded the model files from the google drive and ran this command:

```
 python src/evaluation/test.py --model CAML --gpu 3 --eval_dataset Aircraft  --fe_type timm:vit_base_patch16_clip_224.openai:768
```

Everything seems to be working as expected:
![Screen Shot 2024-09-07 at 6 03 45 PM](https://github.com/user-attachments/assets/e7ad5685-f2ec-4548-9d61-78572b340479)

**Comment by cfifty** [comment]
Did you change any parts of the code or simply run it as-is? It really looks as if you are reversing the labels at some point. Can you try a very simple example (batch size of 1 and look at the assignment of labels to examples ++ try reversing these).

**Comment by ctoa2020** [comment]
Dear cfifty,
Right. When test.py loads the checkpoint file "model.pth" from the google drive, the testing works as expected as the snapshot you provide. But when test.py loads the checkpoint file produced by train.py that is trained by exactly following the training configurations in README.md, we still don't get the expected results yet.
We are very sure that we did not change any parts of the code and we just simply run it as-is. Next, we will follow your suggestion to try the very simple example of batch_size of 1, but we don't quite understand what you mean by "look at the assignment of labels of examples ++ try reversing these". Could you give us more detailed information(e.g. which variables or data structures in the code) about the assignment of labels that we need to observe or reverse?
Many thanks.

**Comment by cfifty** [comment]
Huh. That's quite weird. You'd want to look at [meta_test](https://github.com/cfifty/CAML/blob/df391c02ccc876f1d14e71de32e53694ffd151e7/src/models/CAML.py#L67). For example: 
```
support_features = feature_vector[:way * shot][::-1]
```
and/or 
```
query_features = feature_vector[way * shot:][::-1]
```

**Comment by ctoa2020** [comment]
Dear cfifty,
We tried to observe the two tensors as you suggested when doing testing, but the "`[::-1]`" indexing method did not work(as shown in snap1.png and snap2.png). It could work when "`[::-1]`" was changed to "`[:-1]`" (as shown in snap3.png and snap4.png), but we were not sure if this was what you originally suggested to observe.
Now we can explore `support_features = feature_vector[:way * shot] `and `query_features = feature_vector[way * shot:]`, both of which are of size [`25, 768]`, and `support_features_1 = feature_vector[:way * shot][:-1]` and `query_features_1 = feature_vector[way * shot:][:-1]`, both of which are of size `[1, 768]`, respectively. However, we still don't know what their values ​​should be to be meaningful. Could you give us more detailed information? 
Many thanks.
![snap4](https://github.com/user-attachments/assets/359924a7-1c51-4953-a59b-eb38f7b74732)
![snap3](https://github.com/user-attachments/assets/5b6a676f-5db9-4a95-a3d0-86cdd2cf47f9)
![snap2](https://github.com/user-attachments/assets/1fb21469-7bb9-4b69-ae92-a75d9aee4349)
![snap1](https://github.com/user-attachments/assets/7f6f3405-4a16-40c6-8c31-73bb745fd3b2)

**Comment by ctoa2020** [comment]
Dear cfifty,
We eventually found out the solution. In our case when training, `query_labels = torch.flip(query_labels, dims=[0])` in `metric_train_fn()` must be commented. When testing, regardless of whether the same code in `metric_eval_fn()` was commented or not, the results were as well as expected.
Finally, many thanks for your kindly help.
