### ISSUE TITLE
I encountered some strange issues when training and testing

### ISSUE THREAD

**Issue by helloworld-zj** [cfifty/CAML#18]
Hello, author. After reading your work and attempting to reproduce the code, I encountered some strange issues that I hope you can clarify:

Why do we flip the labels of the query set each time? However, the same operation is not performed on the data of the query set. Doesn’t this cause a mismatch between the two? The corresponding code is: query_labels = torch.flip(query_labels, dims=[0]).

When I was testing, I found that why does the data of each class in the query set need to be adjacent? That is, the predictions are correct only when the data is arranged like this: (class1_img1, class1_img2... class2_img1, class2_img2... classn_imgn). But when my query data is randomly arranged, such as (class1_img1, class3_img1, class1_img2...), the predictions are completely wrong. (Of course, the true labels and images are completely matched).

I look forward to your reply. Thank you very much!

**Comment by cfifty** [comment]
See: 
1. https://github.com/cfifty/CAML/issues/4
2. https://github.com/cfifty/CAML/issues/14
