### ISSUE TITLE
Using parameter timm: vit_huge_patch14_clip_224.laion2b: 1280, there is a bug present

### ISSUE THREAD

**Issue by 1148270327** [cfifty/CAML#19]
--fe_type timm:vit_huge_patch14_clip_224.laion2b:1280

When I use this parameter, I encounter problems and have discovered the following bug:
1. There is an issue with the download URL, and the Timm download links are all invalid. The URL path/resolve/main/model.safensors should be changed to/tree/main/model.safensors

2. For this parameter, a dimension mismatch will be prompted, and the dimension of the model is torch.Size([5, 1024]) ， And the dimension of laion2b is torch.Size([5, 1536])

3. The logic on line 19 of the utli.py code is incorrect. As shown in the parameter above, it not only contains ‘laion’ but also ‘clip’ string.
4. 
<img width="825" alt="image" src="https://github.com/user-attachments/assets/b1d0e998-1ea1-4573-a7c2-afcbb4723770" />

**Comment by 1148270327** [comment]
This is the Timm model file I downloaded,  pic.
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/4be61a11-30a0-4df4-a69d-4f4940bbe4cb" />
This is the laion2b model file I downloaded, pic.
<img width="745" alt="image" src="https://github.com/user-attachments/assets/bea282c5-1499-4807-9062-de515c76cbd3" />
with above resourse ， will result in a dimension mismatch。
<img width="1534" alt="image" src="https://github.com/user-attachments/assets/e2fe665e-d854-4f05-879a-f3b0d9566463" />


another way, I have tried this parameter timm: vit_base_patch16_clip_224.openai: 768 downloads, it is possible to manually download the corresponding resources

**Comment by 1148270327** [comment]
After some debugging, the link for downloading and accessing the code is 'https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_model.safetensors'. which can not be found in huggface. 
The error above is that I manually downloaded the model from CLIP-ViT-H-14-laion2B-s32B-b79K, but found that it has 1024 dimensions.

Can you please provide the link to the Timm model file that is still available？

**Comment by 1148270327** [comment]
which model?
![image](https://github.com/user-attachments/assets/87337664-b58e-4510-a1d6-cc400b00029e)

**Comment by cfifty** [comment]
Referring to your first comment:

1. The download is automatic; I've tested this to confirm it continues to work tonight. Did you not follow the comment in train.py? Here's a link to the model card: https://huggingface.co/timm/vit_huge_patch14_clip_224.laion2b. 
2. See 1. 

For 3 and 4, this is a mistake I made during the refactor for public release. Can you open a PR?

**Comment by 1148270327** [comment]
Thank you for providing the actual download link. The code was downloaded from the main branch by me, and I estimate that it needs to be modified to correct the download to the correct timm model.
![image](https://github.com/user-attachments/assets/2ebd1b15-68a7-4816-b96e-9e0351adc52f)
The program may automatically redirect.
other way, I can not open a PR, it is illegal to access GitHub\Huggface in China. I accessed it through an illegal proxy.

**Comment by 1148270327** [comment]
I replaced it with the model in this link later, and the dimensions are the same, so it can run normally.
https://huggingface.co/timm/vit_huge_patch14_clip_224.laion2b_ft_in12k_in1k

I also noticed that the model repository has just been updated, see the picture below.
![image](https://github.com/user-attachments/assets/17a11130-7c69-46af-90d2-1c17178a899a)

**Comment by cfifty** [comment]
Hey great; the download link is likely not working due to the proxy. I'm glad you were able to find a solution.
