### ISSUE TITLE
testing on other downstream benchmarks

### ISSUE THREAD

**Issue by aymane399** [cfifty/CAML#2]
Hello,

If I wish to apply CAML to my own downstream benchmark (for examples 2-ways 20-shots) , would I need to train it the sequence encoder on a similar setting in Imagenet and COCO or can I use the pretrained one?

Thank you

**Comment by cfifty** [comment]
Hey! You should use the pre-trained sequence encoder (no need to re-train it). Just make sure the checkpoint of the pre-trained sequence model matches the Image Encoder used to train it (CLIP, Laion-2b, or ResNet-34). 

The Laion-2b image encoder results in the best performance of CAML (ViT-huge in Tables 9-12 of the appendix).

Side Note: If n in n-ways exceeds 5, then you would need to re-train the sequence encoder with a n-way ELMES. However, as your n = 2 < 5, this isn't an issue.

**Comment by XPZ07** [comment]
I am also planning to use it in downstream tasks. May I ask if the weights in the model have been published? I did not find them in Readme.md
