### ISSUE TITLE
How can I use this model on a custom dataset?

### ISSUE THREAD

**Issue by TeddyPorfiris** [cfifty/CAML#3]
I have my own dataset I would like to perform few shot learning on. How would I go about doing this? Thank you!

**Comment by cfifty** [comment]
Sure, this is quite simple: 

1. Format your dataset like a typical torch ImageDataset: 
```
your_dataset folder/
|
|----test/
|       |     class_1/
|       |      | img_1.jpg
|       |      | img_2.jpg
|       |      | ...
|       |     class_2/
|       | ...
```
You find see an example of this if you download the eval datasets and click into any of the downstream dataset folders. We want to make your dataset look like those.

2. Then run the command to test on this dataset (see the ReadMe.md: ```python src/evaluation/test.py ...```)

**Comment by 1148270327** [comment]
greate work! 
but, I don't quite understand how to fine tune a custom small sample set , then input an image for predicting categories.
 As mentioned above, it's just for evaluating/testing pre trained models.

**Comment by cfifty** [comment]
Hey! You're not supposed to fine-tune on a custom small sample set. That's the power of in-context learning: it works without fine-tuning. 

Simply pass the examples through the model, and you'll get a probability distribution over the different classes (that are defined in the input).

**Comment by 1148270327** [comment]
> Hey! You're not supposed to fine-tune on a custom small sample set. That's the power of in-context learning: it works without fine-tuning.
> 
> Simply pass the examples through the model, and you'll get a probability distribution over the different classes (that are defined in the input).

Thank you for your reply. 
What I understand is to promptly load our own small sample category data as context and publish it as a service, then input an image and output the category.
 Is that so? Can you provide a usable example

**Comment by 1148270327** [comment]
Also, I would like to know why we need to use two models， one loaded in Timm , another  pretraining datasets Laion-2b image embeddings。
sorry, My English is not very good(不好意思，我的英语水平有点差)
