### ISSUE TITLE
Base ViT-small & ViT-tiny pretrain model/weight

### ISSUE THREAD

**Issue by DickHanselRyan** [cfifty/CAML#8]
Hi authors,

I would like to ask about the pretrain model/weight you provided. I'm currently using base ViT model with 16 patches on my project, if I want to use the pretrain model you provided, do you have any suggestion to use which pretrain model/weight?

Thank you for your help

**Comment by cfifty** [comment]
Hey -- if you want to reproduce the results in the main text of the paper, use the weights in the ```CAML_CLIP``` folder. If you want to maximize the performance of CAML (see appendix tables), use CAML with the Laion2b weights. 

Just make sure the feature encoder is set to CLIP (or laion2b) to match the weights of the transformer encoder.
