### ISSUE TITLE
How to use model with way != 5

### ISSUE THREAD

**Issue by PierreCarceller** [cfifty/CAML#9]
Thanks for this great project/paper!

I've managed to run your code with Way = 5.

As I understand it, if I want to use a different setting (e.g. way = 10) I have to reboot the model. Am I right?

**Comment by cfifty** [comment]
Thanks! You can run way <= 5; however, if way > 5, you would need to re-train the model from scratch (i.e. on the combined ImageNet-1k, Fungi, MSCOCO, etc. dataset) with the way = n setting. This is because the ELMES is a fixed set of vectors [so you can always go down, but not up].
